export const SET_SEARCH_DATA = 'SET_SEARCH_DATA';
export const FETCH_SEARCH_DATA = 'FETCH_SEARCH_DATA';
export const SET_SELECTED_SONG = 'SET_SELECTED_SONG';
export const FETCH_SELECTED_SONG = 'FETCH_SELECTED_SONG';
